FROM openjdk:11-jdk
ENV	USE_PROFILE release
ENV CHOKIDAR_USEPOLLING=true
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=${USE_PROFILE}", "-jar","/app.jar"]