server:
  port: 8082

tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8003

spring:
  profiles:
    active: debug
  web:
    resources:
      static-locations: classpath:classpath:/resources/, classpath:/templates/
---
spring:
  profiles: debug
  datasource:
    username: ENC(cXhco38oKWp70Gim8YIEWg==)
    password: ENC(m1fDDBKYMSYasrm/fVJbpxXq5gRL8gPb)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(jhcOLhL/VYUrGddFvkL9uQH+nkwGjdcjIuZsTT+5JvZop9YG7ncAVRRUpGsOAjDitfKl+5A0B+S7Is5B1eVqxrAI2WKTYuzudzQTeVPgcoA=)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring: 
  profiles: release
  datasource:
    username: ENC(Pdzg771IDdfuxx3lw5MWlA==)
    password: ENC(R6sHhKvvPzAy3xrKPxNz0RZSmA4SuG49)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(1ob6kQa3ayRbiUZUj1eqI9JUqtKIHfRrXzCeeq1nq9h1R8F8ug/sDqo0bg+IL94GdwaE9AZx5rYBOrGvuciFGg==)

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
      main:
        allow-bean-definition-overriding: true
    database: default
---
kafka:
   bootstrapAddress: localhost:9092
message:
   topic: mytopic
jasypt:
  encryptor:
    bean: jasyptStringEncryptor    

