server:
  port: 8082

tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8003

spring:
  profiles:
    active: debug
  web:
    resources:
      static-locations: classpath:classpath:/resources/, classpath:/templates/
---
spring:
  profiles: debug
  datasource:
    username: ENC(cXhco38oKWp70Gim8YIEWg==)
    password: ENC(m1fDDBKYMSYasrm/fVJbpxXq5gRL8gPb)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(YJVM4LL6ba76nTxl7RSDzSoR2olcGlLSRmhzjs9oAqjdJgQIJiiORBuLrSBXrNeWXocsSArv/b9yjnOQ+G2DMxedp3dO7dVeyv7zfS1mg5NyI0wSwQI4MfwYq6gPPAbT3IZjaXVHQ57IaUBpH3zFgyNfgFk5Qs2IKlzfdakIPDUVLOJGZ3xALxbxZxea4pYzBIQbZO1oVbQ0N87hztkOxz8TqGYFAH2MCTM7BmUqH11xj2t0skbJP0y6c2ZtyIxyLWhTegcPpIFBFicX/iaLL8VM+9mkl2M3xuDVPCnLKV5Y8WOeEkBa/j8orJIqtxlCWsuHTwcSJFTHLklPhvt4sicF5XfXvYqJoh0fAn68W5lDsqhCzeDlajbL2DpqSGEJ5DlgJYwQmZQP6511y7/T6cSlhLHK1A2Wh+y/5zxsztacChAgMe2yzDZFUoVV3zrdLDH31Sypk8zvlWCo3qv1AyFRu/wRBA+OIw4W5sHun3zGVZvxRvVpVZMQBjJvRpda)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring: 
  profiles: release
  datasource:
    username: ENC(Pdzg771IDdfuxx3lw5MWlA==)
    password: ENC(R6sHhKvvPzAy3xrKPxNz0RZSmA4SuG49)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(6WOiU9s/wHbi4DjV/OWS+JmGThLzBOWD2hydsEwbNKORWDoDZJ5AyZpnel/9D3gb4rFWeDHbJk9cmt+mt5qU8ZiG7dRzQtaqp8ZO/aRl5XUJPI9aebqESsE7hOxYqDaL4cJjvfPv6hwXq84zT9D8DL7RZoYxkPo/p20Al2dBiFhtvmXcEpLpxZfcytO0kDhafbnvtQ0eR60EbiL8EA5p9g2ty+hBvVyykg0/aPCkyE43qPgdf4VZ3/8Y7E5S6cJn6YHyGm+2YjlRVWSZuAL7ZffOnHoih3pd0fh95MRGpAvNGGSY1W51YYAPoz3RPkdfKuuSmSuJYk0XoDRXqPqQr33njVj0GTmKVeHSFcmnEVjQzk3LTkr2o+rIy2takxEsgaKIqBk+EJpgaZ/VoSxUsR6l744ZaiEjPo3CxdwLqKPH0wG9ee4cMoksJHvXEvmM0vYDrRGaVwWKuuLzeNe5tm/SGCDjETHUxG918BvOsBwzYHu0Kf/ZknxdLka6N3ME)

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
      main:
        allow-bean-definition-overriding: true
    database: default
---
kafka:
   bootstrapAddress: localhost:9092
message:
   topic: mytopic
jasypt:
  encryptor:
    bean: jasyptStringEncryptor    

